export const properties = [
  {
    id: 0,
    name: "edgewood",
    thumbnail: "images/EDGEWOOD/edgewood-main.jpg",
    description:
      "4 BEDROOMS, 3 ½ BATHS, HEATED GUNITE POOL & SPA, A.C, FULLY FURNISHED",
    images: [
      require("/public/images/EDGEWOOD/edgewood-1.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-2.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-3.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-4.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-5.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-6.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-7.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-8.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-9.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-10.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-11.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-12.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-13.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-14.gif"),
      require("/public/images/EDGEWOOD/edgewood-15.gif"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3013.7407527073597!2d-72.29293457546913!3d40.943348655885316!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bdd1c9105a51%3A0xc2b969fc74cbdab!2s132%20Edgewood%20Ave%2C%20Bridgehampton%2C%20NY%2011932%2C%20USA!5e0!3m2!1sen!2sjp!4v1647856741818!5m2!1sen!2sjp",
  },
  {
    id: 1,
    name: "sag harbor village",
    thumbnail: require("/public/images/SAG-HARBOR/sag-harbor-village-main.jpg"),
    description:
      "4 BEDROOMS, 3 ½ BATHS, HEATED GUNITE POOL & SPA, A.C, FULLY FURNISHED",
    images: [
      require("/public/images/SAG-HARBOR/sag-harbor-village-a-1.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-a-2.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-a-3.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-a-4.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-a-floorplan.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-b-1.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-b-2.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-b-3.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-b-4.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-b-floorplan.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-c-1.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-c-2.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-c-3.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-c-floorplan.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-d-1.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-d-2.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-d-3.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-d-4.jpeg"),
      require("/public/images/SAG-HARBOR/sag-harbor-village-d-floorplan.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3011.2782585345485!2d-72.29021748433459!3d40.99728242804975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bd213525b741%3A0xc1d520ea9f3ef158!2s87%20Hampton%20St%2C%20Sag%20Harbor%2C%20NY%2011963%2C%20USA!5e0!3m2!1sen!2sjp!4v1647926284450!5m2!1sen!2sjp",
  },
  {
    id: 2,
    name: "stephen hands",
    thumbnail: require("/public/images/STEPHEN-HANDS/stephen-hands-main.jpg"),
    description:
      "3 BEDROOMS, 2 BATHS, OIL HEAT, UNFURNISHED, ALL APPLIANCES, 20'X40' HEATED VINYL POOL",
    images: [
      require("/public/images/STEPHEN-HANDS/stephen-hands-1.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-2.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-3.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-4.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-5.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-6.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-7.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-8.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-9.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-10.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-11.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-12.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-13.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-14.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3012.7146238416076!2d-72.22702438433528!3d40.96583012998408!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bb79d71548c7%3A0x193bf37835a248ef!2s199%20Stephen%20Hands%20Path%2C%20East%20Hampton%2C%20NY%2011937%2C%20USA!5e0!3m2!1sen!2sjp!4v1647862665046!5m2!1sen!2sjp",
  },
  {
    id: 3,
    name: "rosehill",
    thumbnail: require("/public/images/ROSEHILL/rosehill-main.jpg"),
    description:
      "3 BEDROOMS, 2 BATHS, OIL HEAT, UNFURNISHED, ALL APPLIANCES, 20'X40' HEATED VINYL POOL",
    images: [
      require("/public/images/ROSEHILL/rosehill-1.jpeg"),
      require("/public/images/ROSEHILL/rosehill-2.jpeg"),
      require("/public/images/ROSEHILL/rosehill-3.jpeg"),
      require("/public/images/ROSEHILL/rosehill-4.jpeg"),
      require("/public/images/ROSEHILL/rosehill-5.jpeg"),
      require("/public/images/ROSEHILL/rosehill-6.jpeg"),
      require("/public/images/ROSEHILL/rosehill-7.jpeg"),
      require("/public/images/ROSEHILL/rosehill-8.jpeg"),
      require("/public/images/ROSEHILL/rosehill-8.gif"),
      require("/public/images/ROSEHILL/rosehill-9.gif"),
      require("/public/images/ROSEHILL/rosehill-10.jpeg"),
      require("/public/images/ROSEHILL/rosehill-11.jpeg"),
      require("/public/images/ROSEHILL/rosehill-12.jpeg"),
    ],
    map: "",
  },
  {
    id: 4,
    name: "elybrook",
    thumbnail: require("/public/images/ELYBROOK/elybrook-main.jpg"),
    description:
      "4 BEDROOMS, 3½ BATHS, 18'x44' HEATED GUNITE POOL & SPA A.C., OIL HEAT, FULLY FURNISHED, ALL APPLIANCES",
    images: [
      require("/public/images/ELYBROOK/elybrook-1.jpeg"),
      require("/public/images/ELYBROOK/elybrook-2.gif"),
      require("/public/images/ELYBROOK/elybrook-3.jpeg"),
      require("/public/images/ELYBROOK/elybrook-4.jpeg"),
      require("/public/images/ELYBROOK/elybrook-5.jpeg"),
      require("/public/images/ELYBROOK/elybrook-6.jpeg"),
      require("/public/images/ELYBROOK/elybrook-7.jpeg"),
      require("/public/images/ELYBROOK/elybrook-8.jpeg"),
      require("/public/images/ELYBROOK/elybrook-9.jpeg"),
      require("/public/images/ELYBROOK/elybrook-10.jpeg"),
      require("/public/images/ELYBROOK/elybrook-11.jpeg"),
      require("/public/images/ELYBROOK/elybrook-12.jpeg"),
      require("/public/images/ELYBROOK/elybrook-13.jpeg"),
      require("/public/images/ELYBROOK/elybrook-14.jpeg"),
    ],
    map: "",
  },
  {
    id: 5,
    name: "116 copeces",
    thumbnail: require("/public/images/COPECES/copeces-main.jpg"),
    description:
      "2 BEDROOMS, 1 BATH, VINYL POOL, ALL APPLIANCES, OIL HEAT, UNFURNISHED",
    images: [
      require("/public/images/COPECES/copeces-1.jpeg"),
      require("/public/images/COPECES/copeces-2.jpeg"),
      require("/public/images/COPECES/copeces-3.jpeg"),
      require("/public/images/COPECES/copeces-4.jpeg"),
      require("/public/images/COPECES/copeces-5.jpeg"),
      require("/public/images/COPECES/copeces-6.jpeg"),
      require("/public/images/COPECES/copeces-7.jpeg"),
      require("/public/images/COPECES/copeces-8.jpeg"),
      require("/public/images/COPECES/copeces-9.jpeg"),
      require("/public/images/COPECES/copeces-10.jpeg"),
    ],
    map: "",
  },
  {
    id: 6,
    name: "118 copeces",
    thumbnail: require("/public/images/COPECES/copeces-main.jpg"),
    description: "",
    images: [
      require("/public/images/COPECES/copeces-1.jpeg"),
      require("/public/images/COPECES/copeces-2.jpeg"),
      require("/public/images/COPECES/copeces-3.jpeg"),
      require("/public/images/COPECES/copeces-4.jpeg"),
      require("/public/images/COPECES/copeces-5.jpeg"),
      require("/public/images/COPECES/copeces-6.jpeg"),
      require("/public/images/COPECES/copeces-7.jpeg"),
      require("/public/images/COPECES/copeces-8.jpeg"),
      require("/public/images/COPECES/copeces-9.jpeg"),
      require("/public/images/COPECES/copeces-10.jpeg"),
    ],
    map: "",
  },
  {
    id: 7,
    name: "rockville",
    thumbnail: require("/public/images/COPECES/copeces-main.jpg"),
    description: "",
    images: [
      require("/public/images/COPECES/copeces-1.jpeg"),
      require("/public/images/COPECES/copeces-2.jpeg"),
      require("/public/images/COPECES/copeces-3.jpeg"),
      require("/public/images/COPECES/copeces-4.jpeg"),
      require("/public/images/COPECES/copeces-5.jpeg"),
      require("/public/images/COPECES/copeces-6.jpeg"),
      require("/public/images/COPECES/copeces-7.jpeg"),
      require("/public/images/COPECES/copeces-8.jpeg"),
      require("/public/images/COPECES/copeces-9.jpeg"),
      require("/public/images/COPECES/copeces-10.jpeg"),
    ],
    map: "",
  },
  {
    id: 8,
    name: "antigua",
    description: "",
    thumbnail: require("/public/images/ANTIGUA/antigua-main.jpg"),
    images: [
      require("/public/images/ANTIGUA/antigua-1.jpeg"),
      require("/public/images/ANTIGUA/antigua-2.jpeg"),
      require("/public/images/ANTIGUA/antigua-3.jpeg"),
      require("/public/images/ANTIGUA/antigua-4.jpeg"),
      require("/public/images/ANTIGUA/antigua-5.jpeg"),
      require("/public/images/ANTIGUA/antigua-6.jpeg"),
      require("/public/images/ANTIGUA/antigua-7.jpeg"),
      require("/public/images/ANTIGUA/antigua-8.jpeg"),
      require("/public/images/ANTIGUA/antigua-9.jpeg"),
      require("/public/images/ANTIGUA/antigua-10.jpeg"),
      require("/public/images/ANTIGUA/antigua-11.jpeg"),
      require("/public/images/ANTIGUA/antigua-12.jpeg"),
      require("/public/images/ANTIGUA/antigua-13.jpeg"),
      require("/public/images/ANTIGUA/antigua-14.jpeg"),
      require("/public/images/ANTIGUA/antigua-15.jpeg"),
      require("/public/images/ANTIGUA/antigua-16.jpeg"),
      require("/public/images/ANTIGUA/antigua-17.jpeg"),
      require("/public/images/ANTIGUA/antigua-18.jpeg"),
      require("/public/images/ANTIGUA/antigua-19.jpeg"),
      require("/public/images/ANTIGUA/antigua-20.jpeg"),
      require("/public/images/ANTIGUA/antigua-21.jpeg"),
    ],
    map: "",
  },
];
