export const properties = [
  {
    id: 0,
    name: "edgewood",
    thumbnail: require("/public/images/EDGEWOOD/edgewood-main.jpg"),
    description: [
      "This charming 4 bedroom, 3 ½ bath home is snuggled in the private community of The Ludlow Greens Association in Bridgehampton, New York. It is spacious and boasts a large living and dining area along with a fully equipped eat-in kitchen. For your comfort, there is central air conditioning and an oil fired heating system. The house, with a heated 18’ x 44’ gunite swimming pool and gunite spa, is surrounded by heavily landscaped shrubbery and a protected wooded area for your privacy. The large deck provides for sunbathing around the pool and peaceful outdoor dining.",
      "The residence is idyllically located to the villages of Southampton, Sag Harbor, and East Hampton. It is a short walk to the Bridgehampton Train Station, The Hampton Jitney pickup location and the quaint Village of Bridgehampton. The Bridgehampton Shopping Plaza will provide you with all your necessities and is a five minute drive from the house. For the beach lover, a 15 minute bike ride (5 minutes by car) will take you to several of the most beautiful ocean beaches on the east end.",
      "The historic whaling village of Sag Harbor (10 minutes by car) has unique shopping and a large picturesque harbor. Sailing, charter fishing, and waterside dining are all readily available. Public golf is available and can be scheduled at several locations. In choosing this lovely home and spending time in any of the charming villages with all they have to offer you will find the relaxed sophistication you seek by spending your time on the beautiful east end of Long Island.",
    ],
    info: "4 BEDROOMS, 3 ½ BATHS, HEATED GUNITE POOL & SPA, A.C, FULLY FURNISHED",
    images: [
      require("/public/images/EDGEWOOD/edgewood-1.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-2.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-3.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-4.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-5.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-6.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-7.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-8.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-9.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-10.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-11.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-12.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-13.jpeg"),
      require("/public/images/EDGEWOOD/edgewood-14.gif"),
      require("/public/images/EDGEWOOD/edgewood-15.gif"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3013.7407527073597!2d-72.29293457546913!3d40.943348655885316!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bdd1c9105a51%3A0xc2b969fc74cbdab!2s132%20Edgewood%20Ave%2C%20Bridgehampton%2C%20NY%2011932%2C%20USA!5e0!3m2!1sen!2sjp!4v1647856741818!5m2!1sen!2sjp",
  },
  {
    id: 1,
    name: "sag harbor village",
    thumbnail: require("/public/images/SAGHARBOR/sag-harbor-village-main.jpg"),
    description: [
      "These apartments are ideally located in the heart of the historic whaling village of Sag Harbor. It is only a five to ten minute walk to restaurants, Bay Street Theater, the movies, Hampton Jitney, the harbor, the historic whaling museum, Mashashimuet park or the beach.",
      "Sailing, fishing, swimming and boating are all a short distance away. A visit to the nearby Havens beach for a summer swim is three blocks away. In addition the towns of East Hampton, Bridgehampton and Southampton are ten to fifteen minutes by car as well as access to several wonderful ocean beaches.",
      " These apartments have parking on the premises with a laundry facility, lawn care, refuse removal, heating and basic TV cable all included for carefree living in a centrally located convenient environment.",
    ],
    info: "4 BEDROOMS, 3 ½ BATHS, HEATED GUNITE POOL & SPA, A.C, FULLY FURNISHED",
    images: [
      require("/public/images/SAGHARBOR/sag-harbor-village-a-1.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-a-2.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-a-3.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-a-4.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-a-floorplan.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-b-1.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-b-2.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-b-3.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-b-4.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-b-floorplan.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-c-1.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-c-2.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-c-3.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-c-floorplan.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-d-1.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-d-2.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-d-3.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-d-4.jpeg"),
      require("/public/images/SAGHARBOR/sag-harbor-village-d-floorplan.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3011.2782585345485!2d-72.29021748433459!3d40.99728242804975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bd213525b741%3A0xc1d520ea9f3ef158!2s87%20Hampton%20St%2C%20Sag%20Harbor%2C%20NY%2011963%2C%20USA!5e0!3m2!1sen!2sjp!4v1647926284450!5m2!1sen!2sjp",
  },
  {
    id: 2,
    name: "stephen hands",
    thumbnail: require("/public/images/STEPHEN-HANDS/stephen-hands-main.jpg"),
    description: [
      "This contemporary, 3 bedroom, 2 bath home is located just outside the village of East Hampton and is about a 15 minute drive to the villages of Sag Harbor and Bridgehampton.  The open floor plan offers wood floors throughout, large sliding doors and expansive windows.  The cathedral ceilings bring wonderful light to the living and dining areas.  The wood burning brick fireplace is a plus on those cold wintery nights, along with an oil fired heater for your ensured comfort.",
      "The second story boasts large skylights in both the master bedroom and bathroom and the master bathroom is equipped with a Jacuzzi tub so you can relax while viewing the stars.  The house has a fully equipped kitchen and is designed for efficient ease while cooking as well as relaxed entertaining through easy dining and living room access.  A 20’ x 40’ vinyl swimming pool offers summertime relaxation with a large deck that extends off the house and surrounds the pool in the private, wooded back yard.",
      "East Hampton village is less than a 10 minute drive from the house and offers the Hampton Jitney, the train station, retail shopping, restaurants, ocean beaches, the John Drew Theatre and the East Hampton movie theatre, just to name a few.  The village of Sag Harbor, an old whaling port, also has a lot to offer in the way of entertainment.  You will have access to art galleries, antique shops, museums and wonderful restaurants.  The Bay Street Theatre offers plays throughout the summer season for both children and adults alike.  Sag Harbor is one of the most picturesque natural harbors on Long Island and sailing and fishing charters are available at many of the marinas in town.",
    ],
    info: "3 BEDROOMS, 2 BATHS, OIL HEAT, UNFURNISHED, ALL APPLIANCES, 20'X40' HEATED VINYL POOL",
    images: [
      require("/public/images/STEPHEN-HANDS/stephen-hands-1.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-2.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-3.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-4.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-5.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-6.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-7.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-8.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-9.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-10.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-11.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-12.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-13.jpeg"),
      require("/public/images/STEPHEN-HANDS/stephen-hands-14.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3012.7146238416076!2d-72.22702438433528!3d40.96583012998408!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bb79d71548c7%3A0x193bf37835a248ef!2s199%20Stephen%20Hands%20Path%2C%20East%20Hampton%2C%20NY%2011937%2C%20USA!5e0!3m2!1sen!2sjp!4v1647862665046!5m2!1sen!2sjp",
  },
  {
    id: 3,
    name: "rosehill",
    thumbnail: require("/public/images/ROSEHILL/rosehill-main.jpg"),
    description: [
      " 3 Rosehill Road is a 3 bedroom 2 bath comtempory house located in the woods of East Hampton. This open living space with all wood floors offers a fully equipped kitchen, which opens to a dining and living room that is not only spacious but full of natural light from the large glass windows and sliding doors that extend the width of the house. The wood burning brick fireplace adds warmth to this open floor plan along with oil fired heat for your comfort. The master bedroom with en-suite and Jacuzzi tub also boost large glass sliding doors and wonderful skylights to watch the night skies by. The large deck with patio and dining furniture extends to the 24’ x 40’ heated swimming pool for your summer dining enjoyment and relaxation. The home is surrounded by the fenced large Northwest Woods Pine trees which give privacy to your outdoor activities.",
      "Located approximately 10 minutes from the Historic Whaling Village of Sag Harbor you will have access to local retail shopping, art galleries, antiquing, museums, fishing and sailing. The Bay Street Theater is located on the Long Wharf and features plays throughout the summer for both children and adults. The Harbor features one of the most beautiful natural harbors on Long Island where one can sit and enjoy not only the scenery, but the acclaimed restaurants. The Town of East Hampton is a 20 minute drive and offers much in the way of entertainment, ocean beaches, John Drew Theater, restaurants and all high end retail shopping is at your disposal.",
    ],
    info: "3 BEDROOMS, 2 BATHS, OIL HEAT, UNFURNISHED, ALL APPLIANCES, 20'X40' HEATED VINYL POOL",
    images: [
      require("/public/images/ROSEHILL/rosehill-1.jpeg"),
      require("/public/images/ROSEHILL/rosehill-2.jpeg"),
      require("/public/images/ROSEHILL/rosehill-3.jpeg"),
      require("/public/images/ROSEHILL/rosehill-4.jpeg"),
      require("/public/images/ROSEHILL/rosehill-5.jpeg"),
      require("/public/images/ROSEHILL/rosehill-6.jpeg"),
      require("/public/images/ROSEHILL/rosehill-7.jpeg"),
      require("/public/images/ROSEHILL/rosehill-8.jpeg"),
      require("/public/images/ROSEHILL/rosehill-8.gif"),
      require("/public/images/ROSEHILL/rosehill-9.gif"),
      require("/public/images/ROSEHILL/rosehill-10.jpeg"),
      require("/public/images/ROSEHILL/rosehill-11.jpeg"),
      require("/public/images/ROSEHILL/rosehill-12.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3011.5673554481464!2d-72.24927778433462!3d40.99095362843918!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bca4a0d2ac25%3A0x4ae3b66524feadd2!2s3%20Rose%20Hill%20Rd%2C%20East%20Hampton%2C%20NY%2011937%2C%20USA!5e0!3m2!1sen!2sjp!4v1647930396616!5m2!1sen!2sjp",
  },
  {
    id: 4,
    name: "elybrook",
    thumbnail: require("/public/images/ELYBROOK/elybrook-main.jpg"),
    description: [
      "This lovely fully furnished 2 story house is located in the Northwest Woods of East Hampton. This is where you can relax by the gunite swimming pool on a hot summer day or curl up by the large fireplace on a snowy winter night. The spacious 4 bedroom 31/2 bath house with wood floors throughout has a large fully equipped eat in kitchen, living room and dining room. French doors in both the kitchen and dining area give access to not only a large deck with patio and dining furniture for your relaxation and dining, but to the 18’x44’ gunite heated pool and spa that is surrounded by privacy landscaping on this oversized property. The house has central air conditioning and an oil fired heating system for your cooling and heating comfort.",
      "The Elybrook House is located a short ten minute drive to the Village of East Hampton. The village offers a diverse shopping menu featuring many retail stores, restaurants, movie theater, fitness gyms, Hampton Jitney, and East Hampton Train Station. With a 15 minute drive you can be relaxing on some of the most beautiful ocean beaches in the Hamptons.",
      "Sag Harbor Village is a 20 minute drive from your location and is a place any vacationer should visit. This historic whaling village offers unique shopping, antique shops, and art galleries. Golfing, sailing, fishing charters and waterside dining are all readily available. In choosing this charming home and spending time in the surrounding area with all that is offered you will find the relaxing experience you deserve here on the East End of Long Island.",
    ],
    info: "4 BEDROOMS, 3½ BATHS, 18'x44' HEATED GUNITE POOL & SPA A.C., OIL HEAT, FULLY FURNISHED, ALL APPLIANCES",
    images: [
      require("/public/images/ELYBROOK/elybrook-1.jpeg"),
      require("/public/images/ELYBROOK/elybrook-2.gif"),
      require("/public/images/ELYBROOK/elybrook-3.jpeg"),
      require("/public/images/ELYBROOK/elybrook-4.jpeg"),
      require("/public/images/ELYBROOK/elybrook-5.jpeg"),
      require("/public/images/ELYBROOK/elybrook-6.jpeg"),
      require("/public/images/ELYBROOK/elybrook-7.jpeg"),
      require("/public/images/ELYBROOK/elybrook-8.jpeg"),
      require("/public/images/ELYBROOK/elybrook-9.jpeg"),
      require("/public/images/ELYBROOK/elybrook-10.jpeg"),
      require("/public/images/ELYBROOK/elybrook-11.jpeg"),
      require("/public/images/ELYBROOK/elybrook-12.jpeg"),
      require("/public/images/ELYBROOK/elybrook-13.jpeg"),
      require("/public/images/ELYBROOK/elybrook-14.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3010.2623504021417!2d-72.21309788433412!3d41.0195159266815!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8a4ea9e8d62b5%3A0xc2c908eb2072436f!2s3%20Ely%20Brook%20Rd%2C%20East%20Hampton%2C%20NY%2011937%2C%20USA!5e0!3m2!1sen!2sjp!4v1647930497786!5m2!1sen!2sjp",
  },
  {
    id: 5,
    name: "116 copeces",
    thumbnail: require("/public/images/COPECES/copeces-main.jpg"),
    description: [
      "This contemporary, 2 bedroom, 1 bath home is located just outside the village of East Hampton.  The open plan offers wood floors throughout.   A row of sliding glass doors in the living and dining areas brighten the downstairs and open right onto the back patio.  Three large skylights upstairs bring wonderful, natural light to the bedrooms and bathroom.    The wood burning brick fireplace is a plus on those cold wintery nights, along with an oil fired heater for your ensured comfort.  Each bedroom features extra-large closets for plenty of storage space. The house has a fully equipped kitchen and is designed for efficient ease while cooking as well as relaxed entertaining through easy dining and living room access.  A 20’ x 40’ vinyl swimming pool offers endless summertime relaxation.   The house boasts a large patio that extends off the house and surrounds the pool in this very private back yard.",
      "East Hampton village is about a 5 minute drive from the house and offers the Hampton Jitney, the train station, retail shopping, restaurants, ocean beaches, the John Drew Theatre and the East Hampton movie theatre, just to name a few.  You will have access to art galleries, antique shops, museums and wonderful restaurants.  The village of Sag Harbor also has a lot to offer in the way of entertainment and is about a 15 minute drive from the house.  Sag Harbor is one of the most picturesque natural harbors on Long Island and sailing and fishing charters are available at many of the marinas in town.",
    ],
    info: "2 BEDROOMS, 1 BATH, VINYL POOL, ALL APPLIANCES, OIL HEAT, UNFURNISHED",
    images: [
      require("/public/images/COPECES/copeces-1.jpeg"),
      require("/public/images/COPECES/copeces-2.jpeg"),
      require("/public/images/COPECES/copeces-3.jpeg"),
      require("/public/images/COPECES/copeces-4.jpeg"),
      require("/public/images/COPECES/copeces-5.jpeg"),
      require("/public/images/COPECES/copeces-6.jpeg"),
      require("/public/images/COPECES/copeces-7.jpeg"),
      require("/public/images/COPECES/copeces-8.jpeg"),
      require("/public/images/COPECES/copeces-9.jpeg"),
      require("/public/images/COPECES/copeces-10.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3010.86974739617!2d-72.17395168433437!3d41.00622402749961!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8a53bd0fe856f%3A0x7b8f7c9425d66967!2s116%20Copeces%20Ln%2C%20East%20Hampton%2C%20NY%2011937%2C%20USA!5e0!3m2!1sen!2sjp!4v1647930570537!5m2!1sen!2sjp",
  },
  {
    id: 6,
    name: "118 copeces",
    thumbnail: require("/public/images/COPECES/copeces-main.jpg"),
    description: [
      "This contemporary, 1 bedroom, 1 bath home is located just outside the village of East Hampton and is about a 15 minute drive to the village of Sag Harbor.  The open plan offers wood floors throughout, large sliding doors and expansive windows.  A row of sliding glass doors on the first floor, bring wonderful light to the living and dining areas.  The wood burning brick fireplace is a plus on those cold wintery nights, along with an oil fired heater for your ensured comfort.  The house has a fully equipped kitchen and is designed for efficient ease while cooking as well as relaxed entertaining through easy dining and living room access. In the back yard, a 15’x38’ vinyl swimming pool with an attached fiberglass spa, offers endless summertime relaxation.",
      "East Hampton village is about a 5 minute drive from the house and offers the Hampton Jitney, the train station, retail shopping, restaurants, ocean beaches, the John Drew Theatre and the East Hampton movie theatre, just to name a few.  The village of Sag Harbor, an old whaling port, also has a lot to offer in the way of entertainment.  You will have access to art galleries, antique shops, museums and wonderful restaurants.  The Bay Street Theatre offers plays throughout the summer season for both children and adults alike.  Sag Harbor is one of the most picturesque natural harbors on Long Island and sailing and fishing charters are available at many of the marinas in town.",
    ],
    info: "1 BEDROOM, 1 BATH, VINYL POOL, OIL HEAT, UNFURNISHED",
    images: [
      require("/public/images/COPECES/copeces-1.jpeg"),
      require("/public/images/COPECES/copeces-2.jpeg"),
      require("/public/images/COPECES/copeces-3.jpeg"),
      require("/public/images/COPECES/copeces-4.jpeg"),
      require("/public/images/COPECES/copeces-5.jpeg"),
      require("/public/images/COPECES/copeces-6.jpeg"),
      require("/public/images/COPECES/copeces-7.jpeg"),
      require("/public/images/COPECES/copeces-8.jpeg"),
      require("/public/images/COPECES/copeces-9.jpeg"),
      require("/public/images/COPECES/copeces-10.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3010.887932215076!2d-72.17409058433428!3d41.00582602752409!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8a53bd2b8eaf5%3A0x9cfc1a26cfa63eb6!2s118%20Copeces%20Ln%2C%20East%20Hampton%2C%20NY%2011937%2C%20USA!5e0!3m2!1sen!2sjp!4v1647930649960!5m2!1sen!2sjp",
  },
  {
    id: 7,
    name: "rockville",
    thumbnail: require("/public/images/COPECES/copeces-main.jpg"),
    description: [
      "The condominiums at Rockville Pike offer many of the advantages you may be looking for while living in Washington D.C. These units are bright and spacious with large living/dining spaces and the kitchen is equipped with updated appliances. During the summer days you have air-conditioning, the nearby pool facility and tennis courts which are easily accessible and a great way to relax.",
      "Rockville’s condominiums have been compared to small village living. The complex has laundry facilities, parking, a subway which is a short walk from your apartment as well as a convenience store, making Rockville Pike Condominiums an ideal location.",
      "The area surrounding the apartment complex has been preserved with beautiful park-like landscaping. You can enjoy reading under a shade tree or sitting by the lake. The designated walking trails along with the well maintained surroundings are wonderful for a stroll or a vigorous run. This setting is a great place to unwind at the end of the day. ",
    ],
    info: "",
    images: [
      require("/public/images/COPECES/copeces-1.jpeg"),
      require("/public/images/COPECES/copeces-2.jpeg"),
      require("/public/images/COPECES/copeces-3.jpeg"),
      require("/public/images/COPECES/copeces-4.jpeg"),
      require("/public/images/COPECES/copeces-5.jpeg"),
      require("/public/images/COPECES/copeces-6.jpeg"),
      require("/public/images/COPECES/copeces-7.jpeg"),
      require("/public/images/COPECES/copeces-8.jpeg"),
      require("/public/images/COPECES/copeces-9.jpeg"),
      require("/public/images/COPECES/copeces-10.jpeg"),
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3097.2830209194462!2d-77.1428404843763!3d39.077250643927094!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89b7cda3889aa823%3A0x5da9b54f8599647e!2s795%20Rockville%20Pike%2C%20Rockville%2C%20MD%2020852%2C%20USA!5e0!3m2!1sen!2sjp!4v1647930736116!5m2!1sen!2sjp",
  },
  {
    id: 8,
    name: "antigua",
    description: [
      "The Gordon House has four bedrooms, three baths and can accommodate up to nine people. Two of the four bedrooms are furnished with queen sized beds and two with twin beds.  All are en-suite with closets and dressing bureaus (linens are provided). The spacious outdoor living and dining areas at the house are part of an extended open air patio furnished with unique Antiguan designs and oversized cushioned chairs. While dining or just relaxing you and your guests will enjoy the 180 degree scenic water views of Dian Bay.  Swimming is off the private, seaside terrace, fifty feet from the house.  For your entertainment the house is equipped with a CD player, cable television, a DVD player and an internet connection. For overseas phone services you can dial direct or receive calls at the house 1-268-463-2050 (billed at a later date).",
      "Marilyn, the cook/housekeeper, can make your vacation especially relaxing by stocking the house with food, cooking breakfast, preparing lunch or, upon request, leaving a cooked meal for your dinner in the refrigerator. House chores such as laundry, making beds and general cleaning are all part of Marilyn’s services. The house also has a complete kitchen with everything a chef could want to prepare a wonderful meal.  To make your arrival simple Amanda, the property manager, can arrange for a car service to greet and escort you from the airport or can assist you in renting a car. Whatever you choose is all available upon request.",
      "This island home is the perfect holiday escape for a couple, family or a group of friends. The villa has a special tranquil ease which flows with its open layout and the fresh breezes of the Caribbean give every visitor a feeling of carefree living. A morning swim off the patio or a sunset walk on the beach will rejuvenate and awaken your senses. Once you have visited the Gordon House you will want to visit time and time again.",
    ],
    info: "",
    thumbnail: require("/public/images/ANTIGUA/antigua-main.jpg"),
    images: [
      require("/public/images/ANTIGUA/antigua-1.jpeg"),
      require("/public/images/ANTIGUA/antigua-2.jpeg"),
      require("/public/images/ANTIGUA/antigua-3.jpeg"),
      require("/public/images/ANTIGUA/antigua-4.jpeg"),
      require("/public/images/ANTIGUA/antigua-5.jpeg"),
      require("/public/images/ANTIGUA/antigua-6.jpeg"),
      require("/public/images/ANTIGUA/antigua-7.jpeg"),
      require("/public/images/ANTIGUA/antigua-8.jpeg"),
      require("/public/images/ANTIGUA/antigua-9.jpeg"),
      require("/public/images/ANTIGUA/antigua-10.jpeg"),
      require("/public/images/ANTIGUA/antigua-11.jpeg"),
      require("/public/images/ANTIGUA/antigua-12.jpeg"),
      require("/public/images/ANTIGUA/antigua-13.jpeg"),
      require("/public/images/ANTIGUA/antigua-14.jpeg"),
      require("/public/images/ANTIGUA/antigua-15.jpeg"),
      require("/public/images/ANTIGUA/antigua-16.jpeg"),
      require("/public/images/ANTIGUA/antigua-17.jpeg"),
      require("/public/images/ANTIGUA/antigua-18.jpeg"),
      require("/public/images/ANTIGUA/antigua-19.jpeg"),
      require("/public/images/ANTIGUA/antigua-20.jpeg"),
      require("/public/images/ANTIGUA/antigua-21.jpeg"),
    ],
    map: "",
  },
];
