export const properties = [
  {
    id: 0,
    name: "edgewood",
    thumbnail: "images/EDGEWOOD/edgewood-main.jpg",
    description:
      "4 BEDROOMS, 3 ½ BATHS, HEATED GUNITE POOL & SPA, A.C, FULLY FURNISHED",
    images: [
      "../../images/EDGEWOOD/edgewood-1.jpeg",
      "../../images/EDGEWOOD/edgewood-2.jpeg",
      "../../images/EDGEWOOD/edgewood-3.jpeg",
      "../../images/EDGEWOOD/edgewood-4.jpeg",
      "../../images/EDGEWOOD/edgewood-5.jpeg",
      "../../images/EDGEWOOD/edgewood-6.jpeg",
      "../../images/EDGEWOOD/edgewood-7.jpeg",
      "../../images/EDGEWOOD/edgewood-8.jpeg",
      "../../images/EDGEWOOD/edgewood-9.jpeg",
      "../../images/EDGEWOOD/edgewood-10.jpeg",
      "../../images/EDGEWOOD/edgewood-11.jpeg",
      "../../images/EDGEWOOD/edgewood-12.jpeg",
      "../../images/EDGEWOOD/edgewood-13.jpeg",
      "../../images/EDGEWOOD/edgewood-14.gif",
      "../../images/EDGEWOOD/edgewood-15.gif",
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3013.7407527073597!2d-72.29293457546913!3d40.943348655885316!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bdd1c9105a51%3A0xc2b969fc74cbdab!2s132%20Edgewood%20Ave%2C%20Bridgehampton%2C%20NY%2011932%2C%20USA!5e0!3m2!1sen!2sjp!4v1647856741818!5m2!1sen!2sjp",
  },
  {
    id: 1,
    name: "sag harbor village",
    thumbnail: "../images/sag-harbor-main.jpg",
    description:
      "4 BEDROOMS, 3 ½ BATHS, HEATED GUNITE POOL & SPA, A.C, FULLY FURNISHED",
    images: [
      "../images/sag-harbor-village-a-1.jpeg",
      "../images/sag-harbor-village-a-2.jpeg",
      "../images/sag-harbor-village-a-3.jpeg",
      "../images/sag-harbor-village-a-4.jpeg",
      "../images/sag-harbor-village-a-floorplan.jpeg",
      "../images/sag-harbor-village-b-1.jpeg",
      "../images/sag-harbor-village-b-2.jpeg",
      "../images/sag-harbor-village-b-3.jpeg",
      "../images/sag-harbor-village-b-4.jpeg",
      "../images/sag-harbor-village-b-floorplan.jpeg",
      "../images/sag-harbor-village-c-1.jpeg",
      "../images/sag-harbor-village-c-2.jpeg",
      "../images/sag-harbor-village-c-3.jpeg",
      "../images/sag-harbor-village-c-floorplan.jpeg",
      "../images/sag-harbor-village-d-1.jpeg",
      "../images/sag-harbor-village-d-2.jpeg",
      "../images/sag-harbor-village-d-3.jpeg",
      "../images/sag-harbor-village-d-4.jpeg",
      "../images/sag-harbor-village-d-floorplan.jpeg",
    ],
    map: "",
  },
  {
    id: 2,
    name: "stephen hands",
    thumbnail: "../images/stephen-hands-main.jpg",
    description:
      "3 BEDROOMS, 2 BATHS, OIL HEAT, UNFURNISHED, ALL APPLIANCES, 20'X40' HEATED VINYL POOL",
    images: [
      "../images/stephen-hands-1.jpeg",
      "../images/stephen-hands-2.jpeg",
      "../images/stephen-hands-3.jpeg",
      "../images/stephen-hands-4.jpeg",
      "../images/stephen-hands-5.jpeg",
      "../images/stephen-hands-6.jpeg",
      "../images/stephen-hands-7.jpeg",
      "../images/stephen-hands-8.jpeg",
      "../images/stephen-hands-9.jpeg",
      "../images/stephen-hands-10.jpeg",
      "../images/stephen-hands-11.jpeg",
      "../images/stephen-hands-12.jpeg",
      "../images/stephen-hands-13.jpeg",
      "../images/stephen-hands-14.jpeg",
    ],
    map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3012.7146238416076!2d-72.22702438433528!3d40.96583012998408!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e8bb79d71548c7%3A0x193bf37835a248ef!2s199%20Stephen%20Hands%20Path%2C%20East%20Hampton%2C%20NY%2011937%2C%20USA!5e0!3m2!1sen!2sjp!4v1647862665046!5m2!1sen!2sjp",
  },
  {
    id: 3,
    name: "rosehill",
    thumbnail: "../images/rosehill-main.jpg",
    description:
      "3 BEDROOMS, 2 BATHS, OIL HEAT, UNFURNISHED, ALL APPLIANCES, 20'X40' HEATED VINYL POOL",
    images: [
      "../images/rosehill-1.jpeg",
      "../images/rosehill-2.jpeg",
      "../images/rosehill-3.jpeg",
      "../images/rosehill-4.jpeg",
      "../images/rosehill-5.jpeg",
      "../images/rosehill-6.jpeg",
      "../images/rosehill-7.jpeg",
      "../images/rosehill-8.jpeg",
      "../images/rosehill-8.gif",
      "../images/rosehill-9.gif",
      "../images/rosehill-10.jpeg",
      "../images/rosehill-11.jpeg",
      "../images/rosehill-12.jpeg",
    ],
    map: "",
  },
  {
    id: 4,
    name: "elybrook",
    thumbnail: "../images/elybrook-main.jpg",
    description:
      "4 BEDROOMS, 3½ BATHS, 18'x44' HEATED GUNITE POOL & SPA A.C., OIL HEAT, FULLY FURNISHED, ALL APPLIANCES",
    images: [
      "../images/elybrook-1.jpeg",
      "../images/elybrook-2.gif",
      "../images/elybrook-3.jpeg",
      "../images/elybrook-4.jpeg",
      "../images/elybrook-5.jpeg",
      "../images/elybrook-6.jpeg",
      "../images/elybrook-7.jpeg",
      "../images/elybrook-8.jpeg",
      "../images/elybrook-9.jpeg",
      "../images/elybrook-10.jpeg",
      "../images/elybrook-11.jpeg",
      "../images/elybrook-12.jpeg",
      "../images/elybrook-13.jpeg",
      "../images/elybrook-14.jpeg",
    ],
    map: "",
  },
  {
    id: 5,
    name: "116 copeces",
    thumbnail: "../images/copeces-main.jpg",
    description:
      "2 BEDROOMS, 1 BATH, VINYL POOL, ALL APPLIANCES, OIL HEAT, UNFURNISHED",
    images: [
      "../images/copeces-1.jpeg",
      "../images/copeces-2.jpeg",
      "../images/copeces-3.jpeg",
      "../images/copeces-4.jpeg",
      "../images/copeces-5.jpeg",
      "../images/copeces-6.jpeg",
      "../images/copeces-7.jpeg",
      "../images/copeces-8.jpeg",
      "../images/copeces-9.jpeg",
      "../images/copeces-10.jpeg",
    ],
    map: "",
  },
  {
    id: 6,
    name: "118 copeces",
    thumbnail: "../images/copeces-main.jpg",
    description: "",
    images: [
      "../images/copeces-1.jpeg",
      "../images/copeces-2.jpeg",
      "../images/copeces-3.jpeg",
      "../images/copeces-4.jpeg",
      "../images/copeces-5.jpeg",
      "../images/copeces-6.jpeg",
      "../images/copeces-7.jpeg",
      "../images/copeces-8.jpeg",
      "../images/copeces-9.jpeg",
      "../images/copeces-10.jpeg",
    ],
    map: "",
  },
  {
    id: 7,
    name: "rockville",
    thumbnail: "../images/copeces-main.jpg",
    description: "",
    images: [
      "../images/copeces-1.jpeg",
      "../images/copeces-2.jpeg",
      "../images/copeces-3.jpeg",
      "../images/copeces-4.jpeg",
      "../images/copeces-5.jpeg",
      "../images/copeces-6.jpeg",
      "../images/copeces-7.jpeg",
      "../images/copeces-8.jpeg",
      "../images/copeces-9.jpeg",
      "../images/copeces-10.jpeg",
    ],
    map: "",
  },
  {
    id: 8,
    name: "antigua",
    description: "",
    thumbnail: "../images/antigua-main.jpg",
    images: [
      "../images/antigua-1.jpeg",
      "../images/antigua-2.jpeg",
      "../images/antigua-3.jpeg",
      "../images/antigua-4.jpeg",
      "../images/antigua-5.jpeg",
      "../images/antigua-6.jpeg",
      "../images/antigua-7.jpeg",
      "../images/antigua-8.jpeg",
      "../images/antigua-9.jpeg",
      "../images/antigua-10.jpeg",
      "../images/antigua-11.jpeg",
      "../images/antigua-12.jpeg",
      "../images/antigua-13.jpeg",
      "../images/antigua-14.jpeg",
      "../images/antigua-15.jpeg",
      "../images/antigua-16.jpeg",
      "../images/antigua-17.jpeg",
      "../images/antigua-18.jpeg",
      "../images/antigua-19.jpeg",
      "../images/antigua-20.jpeg",
      "../images/antigua-21.jpeg",
    ],
    map: "",
  },
];
